default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 12345@Ab
  host: localhost
  port: 5432
  schema_search_path: public
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pharmacy_charity_dev

test:
  <<: *default
  database: pharmacy_charity_test

production:
  <<: *default
  database: pharmacy_charity_prod